from types import SimpleNamespace

from blueprints.admin.routes import create_admin_blueprint
from blueprints.attendance.routes import create_attendance_blueprint
from blueprints.auth.routes import create_auth_blueprint
from blueprints.client_staff.routes import create_client_staff_blueprint
from blueprints.dashboard.routes import create_dashboard_blueprint
from blueprints.guests.routes import create_guests_blueprint
from blueprints.staff.routes import create_staff_blueprint
from blueprints.user.routes import create_user_blueprint

AUTH_DEPS = (
    "db",
    "User",
    "LOGIN_ATTEMPT_SESSION_KEY",
    "PASSWORD_RESET_PATH",
    "ROLE_ADMIN",
    "ROLE_SUPER_ADMIN",
    "ROLE_USER",
    "build_password_template_context",
    "clear_active_login_session_for_current_user",
    "clear_login_throttle",
    "end_login_session",
    "find_login_throttle",
    "get_client_ip",
    "get_current_user",
    "get_form_text",
    "get_login_lockout_remaining_seconds",
    "get_password_title_for_role",
    "get_tracking_session_id",
    "is_login_throttle_locked",
    "is_valid_password_for_role",
    "log_activity_event",
    "log_auth_event",
    "login_required",
    "normalize_phone_number",
    "parse_int",
    "password_matches",
    "register_failed_login",
    "set_account_password",
    "start_login_session",
)

ATTENDANCE_DEPS = (
    "build_guest_attendance_qr_png",
    "build_guest_qr_token",
    "build_guest_qr_svg",
    "build_guest_qr_scan_value",
    "build_inactive_billing_period_message",
    "build_qr_already_verified_message",
    "build_qr_welcome_message",
    "db",
    "format_attendance_time",
    "GUEST_QR_PAGE_TTL_SECONDS",
    "get_attendance_owner_from_token",
    "get_attendance_staff_from_token",
    "get_guest_attendance_verification_status",
    "get_guest_from_qr_token",
    "get_guest_from_short_qr_code",
    "get_request_id",
    "is_owner_in_active_billing_period",
    "log_attendance_event",
    "log_system_error",
    "verify_guest_attendance",
)

DASHBOARD_DEPS = (
    "BillingPayment",
    "DemoGuest",
    "DEFAULT_GUEST_STATUS",
    "GUEST_STATUS_OPTIONS",
    "Guests",
    "ROLE_ADMIN",
    "ROLE_SUPER_ADMIN",
    "ROLE_USER",
    "calculate_account_activation_status",
    "get_current_user",
    "get_current_user_display_name",
    "get_utc_naive_datetime",
    "get_user_display_name",
    "login_required",
    "role_required",
)

CLIENT_STAFF_DEPS = (
    "ROLE_USER",
    "Staff",
    "block_staff_account",
    "build_staff_access_url",
    "build_staff_log_keyword",
    "build_staff_page_context",
    "build_staff_redirect",
    "build_staff_status_items",
    "build_staff_attendance_qr_url",
    "build_staff_attendance_url",
    "clean_staff_name",
    "clean_staff_phone",
    "create_staff_access",
    "db",
    "get_active_staff_access",
    "get_current_user",
    "get_today_staff_log_entries",
    "get_user_display_name",
    "is_owner_in_active_billing_period",
    "generate_staff_attendance_url",
    "format_attendance_token_generated_at",
    "log_activity_event",
    "login_required",
    "revoke_staff_access",
    "role_required",
    "unblock_staff_account",
    "validate_staff_form",
)

STAFF_DEPS = (
    "DEFAULT_GUEST_STATUS",
    "Guests",
    "STAFF_PIN_MAX_ATTEMPTS",
    "block_staff_account",
    "build_manual_guest_data",
    "build_staff_guest_added_by",
    "build_staff_guest_context",
    "build_staff_guest_table_redirect",
    "confirm_attendance_verification_request",
    "clean_guest_status",
    "db",
    "delete_staff_session_cookie",
    "get_accessible_staff_guest",
    "get_current_staff",
    "get_form_text",
    "get_staff_access_by_token",
    "get_staff_display_name",
    "get_staff_attendance_notification",
    "get_staff_owner",
    "get_utc_naive_datetime",
    "is_guest_phone_registered",
    "is_staff_access_idle_expired",
    "log_staff_activity_event",
    "parse_int",
    "reject_attendance_verification_request",
    "revoke_staff_access",
    "set_staff_session_cookie",
    "staff_login_required",
)

GUESTS_DEPS = (
    "ROLE_ADMIN",
    "ROLE_SUPER_ADMIN",
    "ROLE_USER",
    "build_guest_table_redirect",
    "build_guest_whatsapp_invite",
    "build_guest_edit_data",
    "clean_guest_status",
    "db",
    "get_accessible_guest",
    "get_current_user",
    "is_guest_phone_registered",
    "is_owner_in_active_billing_period",
    "log_activity_event",
    "login_required",
    "role_required",
)

USER_DEPS = (
    "BillingPayment",
    "DEFAULT_GUEST_STATUS",
    "Guests",
    "ROLE_USER",
    "UploadValidationError",
    "build_guest_query",
    "build_guest_upload_preview",
    "build_active_guest_export_filename",
    "build_final_archive_excel",
    "build_final_guest_export_filename",
    "build_manual_guest_data",
    "build_user_guest_context",
    "clear_pending_guest_upload",
    "db",
    "format_attendance_time",
    "ensure_final_guest_backup",
    "get_current_user",
    "get_latest_final_archive",
    "get_request_id",
    "get_uploaded_file",
    "is_guest_phone_registered",
    "is_owner_in_active_billing_period",
    "is_premium_user",
    "load_pending_guest_upload",
    "log_activity_event",
    "log_system_error",
    "login_required",
    "parse_int",
    "replace_guest_rows",
    "role_required",
    "save_guest_rows",
    "save_uploaded_guest_file",
    "save_pending_guest_upload",
    "build_inactive_billing_period_message",
    "sync_user_activation_status",
    "verify_guest_qr_attendance",
)

ADMIN_DEPS = (
    "BillingPayment",
    "DEFAULT_ADMIN_PASSWORD",
    "DEFAULT_GUEST_STATUS",
    "DEFAULT_USER_RESET_PASSWORD",
    "Guests",
    "INDONESIA_BANK_OPTIONS",
    "PACKAGE_OPTIONS",
    "ROLE_ADMIN",
    "ROLE_SUPER_ADMIN",
    "ROLE_USER",
    "UploadValidationError",
    "User",
    "build_admin_guest_context",
    "build_admins_redirect",
    "block_account_login",
    "build_active_guest_export_filename",
    "build_final_archive_excel",
    "build_final_guest_export_filename",
    "build_guest_attendance_qr_url",
    "build_guest_upload_preview",
    "build_guest_query",
    "build_whatsapp_settings_context",
    "build_user_list_context",
    "build_users_redirect",
    "clear_pending_guest_upload",
    "db",
    "ensure_final_guest_backup",
    "format_attendance_token_generated_at",
    "format_attendance_time",
    "generate_client_username",
    "generate_guest_attendance_url",
    "get_current_user",
    "get_current_user_display_name",
    "get_form_text",
    "get_manageable_admins",
    "get_min_period_end_date",
    "get_latest_final_archive",
    "get_latest_verified_payment",
    "get_selected_owner_user",
    "get_uploaded_file",
    "handle_upload",
    "is_owner_in_active_billing_period",
    "load_pending_guest_upload",
    "log_activity_event",
    "log_auth_event",
    "login_required",
    "normalize_phone_number",
    "parse_int",
    "parse_iso_date",
    "password_matches",
    "process_guests_upload",
    "replace_guest_rows",
    "role_required",
    "save_guest_rows",
    "save_pending_guest_upload",
    "save_uploaded_guest_file",
    "set_account_password",
    "archive_previous_event_for_reactivation",
    "sync_user_activation_status",
    "sync_users_activation_status",
    "unblock_account_login",
    "save_whatsapp_template",
    "update_whatsapp_api_phone_number_id",
    "update_whatsapp_api_token",
    "update_whatsapp_phone",
    "update_whatsapp_send_mode",
    "validate_admin_form",
    "validate_new_user_form",
)


# Fungsi untuk memilih dependency yang diperlukan oleh Blueprint.
def select_dependencies(deps, names):
    return SimpleNamespace(**{name: getattr(deps, name) for name in names})


# Fungsi untuk mendaftarkan semua Blueprint aplikasi.
def register_app_blueprints(app, deps):
    app.register_blueprint(create_auth_blueprint(select_dependencies(deps, AUTH_DEPS)))
    app.register_blueprint(create_attendance_blueprint(select_dependencies(deps, ATTENDANCE_DEPS)))
    app.register_blueprint(create_dashboard_blueprint(select_dependencies(deps, DASHBOARD_DEPS)))
    app.register_blueprint(create_client_staff_blueprint(select_dependencies(deps, CLIENT_STAFF_DEPS)))
    app.register_blueprint(create_staff_blueprint(select_dependencies(deps, STAFF_DEPS)))
    app.register_blueprint(create_guests_blueprint(select_dependencies(deps, GUESTS_DEPS)))
    app.register_blueprint(create_user_blueprint(select_dependencies(deps, USER_DEPS)))
    app.register_blueprint(create_admin_blueprint(select_dependencies(deps, ADMIN_DEPS)))
